name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    paths:
      - "src/**/*"
      - "package.json"
      - "package-lock.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build legacy
        run: ./scripts/build-and-package.sh legacy

      - name: Build extension
        run: ./scripts/build-and-package.sh extension

      - name: Build modern
        run: ./scripts/build-and-package.sh modern

      - name: Publish artifact
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: um-web-all
          path: *.zip
